### ISSUE TITLE
Add voting section details header

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#100]
All screens should display the header with the info about the current voting section.

![Capture](https://user-images.githubusercontent.com/1358055/66954871-e6726600-f069-11e9-9628-57609fd911d2.JPG)

There should be an option to change the voting section.

The end time for the previous section should be saved automatically when changing stations.

Figma wireframes are available here: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV-mobile?node-id=0%3A1

**Comment by CristiHabliuc** [comment]
This is already implemented by me, the custom VC is called `SectionHUDViewController` (it's already in place in the Section Details VC)

**Comment by CristiHabliuc** [comment]
Closing this issue, we'll reuse the component in each sub screen
