### ISSUE TITLE
Update icons on question screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#114]
- question status icon
- add note icon

Figma available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=26%3A161

![Question](https://user-images.githubusercontent.com/1358055/67567230-302a1300-f732-11e9-88f1-c97e17865996.png)

**Comment by CristiHabliuc** [comment]
Done
