### ISSUE TITLE
Update forms screen to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#115]
- add default form icon
- update icon for sync status section

Figma available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=26%3A161

![Main](https://user-images.githubusercontent.com/1358055/67567444-91ea7d00-f732-11e9-9a4d-a97e4adcbac6.png)

**Comment by CristiHabliuc** [comment]
@aniri is the icon for the sync status section static or is there an animation of some kind?
