### ISSUE TITLE
Update section list screen to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#116]
- add icon for questions that have notes saved
- update icon for questions that have answered saved locally but not synced yet

Figma available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=26%3A161

![Section_list](https://user-images.githubusercontent.com/1358055/67567595-d413be80-f732-11e9-9435-6c312e643cc8.png)

**Comment by CristiHabliuc** [comment]
Implemented
