### ISSUE TITLE
[Bug] Improve back button from choose polling station screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#124]
The screen can be reached in two cases, the back button should have different outcomes:

- first login after onboarding -> back button should close the app
- when the user selects the change polling station action from the header -> the back button should take the user back

**Comment by AlexandraDaraban** [comment]
I can work on this

**Comment by CristiHabliuc** [comment]
The first scenario is not possible in iOS apps. The HIG doesn't allow killing the app on purpose. You can do it by forcing a crash, but it won't get on the App Store with this.

I'll implement the second scenario tho'
