### ISSUE TITLE
No "Add Note" button on the last question of every set

### ISSUE THREAD

**Issue by catileptic** [code4romania/monitorizare-vot-ios#128]
On the last question of every set, the "Add Note" feature is missing. 
Version: `1.1.1 (3)`

![2019-11-01 16 59 33](https://user-images.githubusercontent.com/14028425/68033810-22900280-fcc9-11e9-91ea-d017e119cea9.jpg)

**Comment by catileptic** [comment]
Update: more specifically, when you reach the last question, it initially doesn't have the "Add note" button. But, if you select an answer, any answer, the button appears. 

All other questions have an "Add note" button by default (even before an answer is selected).

**Comment by CristiHabliuc** [comment]
That makes sense. I didn't get to test it on smaller screens. In that scenario, that view should be scrollable, but you're definitely missing the UI element on entry. I'll get it fixed ;)
