### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by pkorpal** [code4romania/monitorizare-vot-ios#197]
I've downloaded the project (dev branch), followed the before you start steps and managed to build and run the app with xcode on a iphone SE2 simulator. I get to the login screen enter some mock data (phone number 123456789 and pin code 1234) and I get an error that says the server can't read the data because it's not in the correct format.

![Zrzut ekranu 2020-06-15 o 13 44 02](https://user-images.githubusercontent.com/22213462/84658284-f2bf0380-af15-11ea-9dde-7d206e008506.png)

My xcode version is 11.5 (11E608c) and I did change the swift version to Swift 5 in the build settings.

**Comment by IrinaBorozanQ** [comment]
the test server is down at the moment :( that's why you are getting this error :( we hope to have it back up soon.

**Comment by pkorpal** [comment]
But we even tried setting up our own server which appears to be running and we get the same error

**Comment by CristiHabliuc** [comment]
Closing this, as it appears it was a server configuration error
