### ISSUE TITLE
Remove rural/urban question

### ISSUE THREAD

**Issue by idormenco** [code4romania/monitorizare-vot-ios#227]
Remove following questions
* Urban/Rural
* Is polling station president female
Add following questions 
* `The number of voters in the electoral roll in a given commission` (integer, required, >0)
* `Number of committee members (integer,required, >0)`
* `Number of women on the committee (integer,required, >0)`
* `Lowest number of committee members present (at time of observation)`  (integer,required, >0)
* `Was the Chairman or Deputy Chairman of the committee always present?` (boolean , same control as Urban/Rural)
* `Is there only one polling station (electoral commission) in the room?` (boolean , same control as Urban/Rural)
* `Was the size of the polling station adequate to the needs of the voting day?` (boolean , same control as Urban/Rural)

**Comment by catalin-casuneanu** [comment]
I can take this one.
