### ISSUE TITLE
Translate app to Polish

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#24]
Reference from Android for the strings: https://github.com/epforgpl/monitorizare-vot-android/blob/master/app/src/main/res/values-pl/strings.xml

**Comment by KrzysztofMadejski** [comment]
Have you checked https://github.com/code4romania/monitorizare-vot-ios/tree/app-localization ? Does it have i18n strings?

**Comment by KrzysztofMadejski** [comment]
@danielmacyszyn is working on that

**Comment by RaduCStefanescu** [comment]
Not connected to current state of project, will close.
