### ISSUE TITLE
Handle multiple dynamic forms

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#27]
Ideally if the could handle unlimited list of forms with different codes and names, such as:
localhost:8080/api/v1/formular/versiune
```json
{
    "versiune": {
        "A": 11,
        "B": 11,
        "C1": 11,
        "C2": 11,
        "Ca": 11,
        "Cb": 11,
        "Cc": 11,
        "Cd": 11,
        "D": 11
    }
}
```

Is it possible relatively easy or is `A` `B` `C` hardcoded into the app? A fast-hack for a while would be to add statically all forms.

**Comment by KrzysztofMadejski** [comment]
Final form names:

A: Przygotowanie
B: Głosowanie
C1: Przekazanie
C2: Liczenie - ogólne
Cg: Liczenie - gmina
Cp: Liczenie - powiat
Cs: Liczenie - sejmik
Cw: Liczenie - wójt
D: Tabulacja

**Comment by RaduCStefanescu** [comment]
This issue is already implemented, please check out:
https://github.com/code4romania/monitorizare-vot-ios/pull/57
