### ISSUE TITLE
Hard-code Polish administrative boundaries

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#28]
So we will have 4 related select boxes: choose
- województwo
- powiat
- gminę
- komisję wyborczą

What would be the easiest way to hard-code it into an iOS app? JSON file? csv? Some enum/other code. I can generate whatever, just let me know how should it look.

**Comment by KrzysztofMadejski** [comment]
Here is a json file with all the regions and districts. 
[districts.zip](https://github.com/code4romania/monitorizare-vot-ios/files/2466673/districts.zip)

**Comment by KrzysztofMadejski** [comment]
On the android it looks as following

![43828472_766198087046161_8765944009647456256_n](https://user-images.githubusercontent.com/849975/46913191-23a4a380-cf91-11e8-9e75-e2de3f0c2936.jpg)

**Comment by RaduCStefanescu** [comment]
Not connected to current project, will close.
