### ISSUE TITLE
Logging-in and choosing polling station should be separate

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#32]
Because these are two use cases:

- Observer want to login to make sure the auth code is ok and he is registered in the system [but the observation hasn't yet started]
- Observation has started and authenticated observer wants to choose polling station

To validate it. Such feat [doesn't exist in Android](https://github.com/code4romania/monitorizare-vot-android/issues/52) so I guess it doesn't exist here as well.

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
