### ISSUE TITLE
After clicking Next on a question the app goes back to Choose Polling Station screen

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#33]
Steps to reproduce:
1. Go into an option Multi with text
2. Click on the button
3. Enter text
4. Click "next" (question)
5. The app goes back to choosing the polling station, the result is not saved

Causes that @danielmacyszyn found:
- [ ] polling station doesn't exist (no error is reported to the interface)
- [ ] function checking if field was filled was not working on singe/multiple with text fields

**Comment by danielmacyszyn** [comment]
In general: every time the app is making a request using a token and something goes wrong - it's being interpreted by the app as an expiration of the token (which doesn't have to be true) and the user is redirected to the root controller (which is also not expected behaviour).

**Comment by RaduCStefanescu** [comment]
This issue is already fixed, please check out:
https://github.com/code4romania/monitorizare-vot-ios/pull/68
