### ISSUE TITLE
Codes of questions not consistent with DB

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#39]
Are not taken from the DB, they are generated while creating view consecutively -> A0 A1 A2 .... These should be taken from DB instead.

**Comment by CristiHabliuc** [comment]
This is now fixed as part of the new API update

**Comment by KrzysztofMadejski** [comment]
Yey! Good job. I'm happy to see mv is moving forward steadily. :)
