### ISSUE TITLE
Catalog of notes: be able to browse through all registered ones

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ios#45]
- [ ] seeing the status of their upload
- [ ] browsing in general as well as browsing ones connected to specific question
- [ ] possibly be able to edit notes

Android cousin: https://github.com/code4romania/monitorizare-vot-android/issues/89

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
