### ISSUE TITLE
Accept dynamic number of forms in mobile app

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ios#53]
Currently the application is hardcoded to pull 3 forms from the backend, using the hardcoded codes for the forms {'A', 'B', 'C'}.

The backend exposes endpoints to request all the forms that are persisted in the backend, as well as requesting each form using the id of the form:
GET /api/v1/formular/versiune
GET /api/v1/formular
For more details please check https://mv-mobile-prod.azurewebsites.net/swagger/ui/index.html

The mobile application should be able to query for and display all the forms defined in the backend.

- [ ] Request and display in the mobile app a list of form ids retrieved from the API
- [ ] Request and display in the mobile app a form based on the id of the form retrieved from the API

**Comment by CristiHabliuc** [comment]
I'm on it

**Comment by RaduCStefanescu** [comment]
In progress @CristiHabliuc
