### ISSUE TITLE
Remove hardcoded form names and description from forms list

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#59]
Currently the form names and short descriptions shown in the forms list screen are hardcoded in the app.

Please use the info retrieved from the call to GET /api/v1/formular

```
"codSectiune": "A"
"descriere": "Deschidere"
```

**Comment by RaduCStefanescu** [comment]
Fixed by https://github.com/code4romania/monitorizare-vot-ios/pull/63
