### ISSUE TITLE
Update app for iOS 13 support

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/monitorizare-vot-ios#79]
Some things have changed in iOS 13, the most important change is the modal presentation style which is not full screen by default anymore, so make sure we handle:

- [x] change the presentation style to full screen where it should be
- [x] make sure the swipe down to dismiss gesture is disabled when there's info to be saved or the user should not be allowed to proceed
- [x] it would be nice to adapt the UI to the iPhone X/Xs/11 where it isn't (use the safe area insets)

**Comment by pankova** [comment]
Hi! I would like to help you with it as part of Hacktoberfest

**Comment by CristiHabliuc** [comment]
Done
