### ISSUE TITLE
[Core] Implement Push Notifications

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/monitorizare-vot-ios#84]
- [ ] Use Firebase to send messages.
- [ ] Minimal implementation (ask for push permissions immediately after log in, if they're not determined, send them to Firebase)
- [ ] See if there's anything to do when a push is received while the app is open or if Firebase handles this

**Comment by aniri** [comment]
Please see related endpoint from BE:
`BE_URL/api/v1/notification/register?ObserverId=1&ChannelName=Firebase&Token=sfgasdgasdgsd`

Swagger for new BE API is available here: http://mv-mobile-test.azurewebsites.net/swagger/index.html
