### ISSUE TITLE
[UI] Update Forms screen

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/monitorizare-vot-ios#86]
Notes:
- [x] Use MvvM
- [x] Use nibs instead of story boards, it makes collaboration easier
- [x] Remove Romanian names from class name, variables etc
- [x] Remove hard coded values, move them into configuration objects/plist/constants

The UI document is [here](https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile?node-id=15%3A2&viewport=50%2C3095%2C0.5925132036209106). Example of new refactoring: https://github.com/code4romania/monitorizare-vot-ios/pull/87 

Old:
![Simulator Screen Shot - iPhone 11 Pro - 2019-09-28 at 11 25 22](https://user-images.githubusercontent.com/1491833/65813830-bfe7aa80-e1e2-11e9-803a-83417c8cd964.png)

New:
![Main](https://user-images.githubusercontent.com/1491833/65813829-b9f1c980-e1e2-11e9-80ee-4abed8a47ff2.png)

**Comment by pankova** [comment]
Hi! I would like to help you with it as part of Hacktoberfest
