### ISSUE TITLE
[UI] Update Notes screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#88]
Notes:
- [x] Use MvvM
- [x] Use nibs instead of story boards, it makes collaboration easier
- [x] Remove Romanian names from class name, variables etc
- [x] Remove hard coded values, move them into configuration objects/plist/constants
- [x] Add menu to allow camera vs gallery picker

The notes should be saved locally and also synced with the backend.

In the new UI, the screen also shows a list of notes that were previously added by the user.  For each note, show the first lines of the text and the date when it was added.

The user can navigate to this screen from two locations: 
- the screen with the forms list <- in this case the previous notes list should show all the notes added in the app
- a question details screen <- in this case the previous notes list should only show the notes related to the current question

The UI document is [here](https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile?node-id=15%3A2&viewport=50%2C3095%2C0.5925132036209106). Example of new refactoring: https://github.com/code4romania/monitorizare-vot-ios/pull/87 

![notes1](https://user-images.githubusercontent.com/1358055/66227140-3ace2b00-e6e5-11e9-9314-b99f6de5f7de.jpg)

![notes2](https://user-images.githubusercontent.com/1358055/66227141-3ace2b00-e6e5-11e9-852f-558ab369f271.jpg)

![notes3](https://user-images.githubusercontent.com/1358055/66227142-3b66c180-e6e5-11e9-9798-d24fa3ed1fe8.jpg)

**Comment by calincrist** [comment]
I can take it.

**Comment by CristiHabliuc** [comment]
Mostly done, will still need to add the menu to allow camera or load from gallery options

**Comment by CristiHabliuc** [comment]
Done, but via action sheet instead of the context menu
