### ISSUE TITLE
Implement button states

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#89]
- Choose polling station screen: 'continue' button should be enabled only if the county and polling station number are filled in
- Polling station details screen: 'continue to forms' button should be enabled only if the area, president and arrival time info are filled in
- Notes Screen: the send note button should be enabled if the user added some text

![buttons](https://user-images.githubusercontent.com/1358055/66227214-64875200-e6e5-11e9-9cbd-5bd82ee225aa.jpg)

complete UI in figma: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile

**Comment by AnupKevins** [comment]
i will working to fix this isuue
