### ISSUE TITLE
[UI] Update Question screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#95]
Notes:
- [x] Use MvvM
- [x] Use nibs instead of story boards, it makes collaboration easier
- [x] Remove Romanian names from class name, variables etc
- [x] Remove hard coded values, move them into configuration objects/plist/constants

The UI document is [here](https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile?node-id=15%3A2&viewport=50%2C3095%2C0.5925132036209106). Example of new refactoring: https://github.com/code4romania/monitorizare-vot-ios/pull/87

**Comment by CristiHabliuc** [comment]
Done
