### ISSUE TITLE
Implement link states

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ios#98]
Update the appearance of the links in the app. Add the tapped state as shown bellow. 

Links from app:
- Question screen: add note to current question
- Notes Screen: add photo video link

![buttons](https://user-images.githubusercontent.com/1358055/66227214-64875200-e6e5-11e9-9cbd-5bd82ee225aa.jpg)

complete UI in figma: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile

**Comment by CristiHabliuc** [comment]
The button at the top is already implemented (the class is named `ActionButton` and is safely IBDesignable)

**Comment by CristiHabliuc** [comment]
The one at the bottom, I suggest not having that type of menu in (the standard behaviour in iOS is [Action Sheets](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/), these context-menu-type of lists are discouraged, unless used on larger screens, such as iPads. Not to mention we get the functionality for free and people are used to this behavior)

**Comment by CristiHabliuc** [comment]
Implemented
